### PR TITLE
Send username when using TURN REST API (fixes #2199)

### LINKED ISSUE #2199: TURN REST API request does not supply username
The janus_turnrest_request function in turnrest.c does not send a username. Which means it does not work with the classical turnhttp-server. Is there a chance to supply it?

### PR DESCRIPTION
**Pull request by lminiero**
See #2199 for context. Untested, so feedback welcome.

### CODE REVIEW

File: turnrest.h [hunk 1]
```diff
@@ -66,8 +66,9 @@ void janus_turnrest_response_destroy(janus_turnrest_response *response);
 
 /*! \brief Retrieve address and credentials for one or more TURN servers
  * @note Use janus_turnrest_response_destroy to get rid of the response, once done
+ * @param[in] user Username to provide in the TURN REST API request
  * @returns A valid janus_turnrest_response instance, if successful, NULL otherwise */
-janus_turnrest_response *janus_turnrest_request(void);
+janus_turnrest_response *janus_turnrest_request(char *user);
```
Comment (tmatth) [inline turnrest.h:71]: nit:  As `char *user` is read-only it might as well be `const char *user`

Comment (lminiero) [reply turnrest.h:71]: Makes sense, I'll fix that, thanks :+1:

**Comment by lminiero** [comment]
Merging.
